replicaCount: 1

appInClusterNamespace: default

targetCluster:
  labelSelector:
    matchLabels:
      #vendor: "ICP"
      #region: "US"
      #environment: Dev
      #datacenter: "toronto"
      #owner: "marketing"
  resourceSelector:
    type: cpu
  compliances: ""

#chartRepoURL: https://mycluster.icp:8443/helm-repo/charts/hub-charts/mynginxapp
chartRepoURL: https://mycluster.icp:8443/helm-repo/charts
